import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    // ignora o "default" e o "template" e poe titulo que estiver no absolute. mas só funciona na página que o absolute estiver definido.
    //absolute: "teste de texto",

    // as páginas que não possuirem titulo definido, vão herdar o título padrão.
    default: "projeto de estudo",

    // cria um template para o titulo das páginas. %s é o título da página atual que está sendo rederizada.
    template: "%s | Next.js",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
